-- script to alter the schema for tables in mimic.db

PRAGMA foreign_keys=off;

BEGIN TRANSACTION;

ALTER TABLE d_cpt RENAME TO _d_cpt_original;

CREATE TABLE d_cpt(
  "ROW_ID" INTEGER NOT NULL PRIMARY KEY,
  "CATEGORY" INTEGER,
  "SECTIONRANGE" TEXT,
  "SECTIONHEADER" TEXT,
  "SUBSECTIONRANGE" TEXT,
  "SUBSECTIONHEADER" TEXT,
  "CODESUFFIX" TEXT,
  "MINCODEINSUBSECTION" INTEGER,
  "MAXCODEINSUBSECTION" INTEGER
);

INSERT INTO d_cpt ("ROW_ID", "CATEGORY", "SECTIONRANGE", "SECTIONHEADER",
                   "SUBSECTIONRANGE", "SUBSECTIONHEADER", "CODESUFFIX",
                   "MINCODEINSUBSECTION", "MAXCODEINSUBSECTION")
  SELECT "ROW_ID", "CATEGORY", "SECTIONRANGE", "SECTIONHEADER",
         "SUBSECTIONRANGE", "SUBSECTIONHEADER", "CODESUFFIX",
         "MINCODEINSUBSECTION", "MAXCODEINSUBSECTION"
  FROM _d_cpt_original;

DROP TABLE _d_cpt_original;

COMMIT;

PRAGMA foreign_keys=on;